appointment/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AppointmentView.as_view(), name='appointment')   
]

healthcare/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('admin/', admin.site.urls),
    path('',include('hospital.urls')),
    path('appointment/',include('appointment.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hospital/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.hospitalView.as_view(), name='hospital'),
    # path('service/', views.service, name='service'),
    # path('schedule/', views.schedule, name='schedule'),

    path('doctor/', views.DoctorListView.as_view(), name='doctor_team'),

    path('contact/', views.ContactView.as_view(), name='contact'),

    # path('about/', views.about, name='about'),
    # path('testimonial/', views.testimonial, name='testimonial'),
]

appointment/models.py
from django.db import models
from django.utils import timezone
from hospital.models import Doctor

class Appointment(models.Model):
    choices_time = (
        ('morning','Morning'),
        ('evening', 'Evening')
    )
    name = models.CharField(max_length=120)
    phone = models.CharField(max_length=11)
    email = models.EmailField()
    doctors = models.ForeignKey(Doctor, on_delete=models.CASCADE, related_name='doctors')
    date = models.DateField(default=timezone.now)
    time = models.CharField(choices=choices_time, max_length=10)
    extra_note = models.TextField(null=True,blank=True)

    
    class Meta:
        verbose_name_plural = "Appointment"

    def __str__(self):
        return f'{self.name} - {self.doctors.name}'

hospital/models.py
from django.db import models

class Doctor(models.Model):
    name = models.CharField(max_length=120)
    speciality = models.CharField(max_length=120)
    picture = models.ImageField(upload_to="doctors/")
    experience = models.TextField()
    
    twitter = models.CharField(max_length=120, blank=True, null=True)
    facebook = models.CharField(max_length=120, blank=True, null=True)
    instagram = models.CharField(max_length=120, blank=True, null=True)

    def __str__(self):
        return self.name

class Testimonial(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField()
    image = models.ImageField(upload_to="feedback/")

appointment/views.py
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View

from hospital.models import Doctor
from .models import Appointment

class AppointmentView(View):
    def get(self, request, *args, **kwargs):
        context = {
            'doctors': Doctor.objects.all()
        }
        return render(request, 'appointment/appointments.html',context)

    def post(self, request, *args, **kwargs):

        name = request.POST.get('name')
        phone = request.POST.get('phone')
        email = request.POST.get('email')
        date = request.POST.get('date')
        time = request.POST.get('time')
        extra_note = request.POST.get('message')
        doctor_id = request.POST.get('doctor')

        if doctor_id:
            doctor = get_object_or_404(Doctor, id=doctor_id)

        if name and phone and email and doctor and date and time and extra_note:
            Appointment.objects.create(name=name, phone=phone, email=email, doctors=doctor,extra_note=extra_note, time=time, date=date)
            messages.success(request,'Appointment done successfully')
        return redirect('appointment')

hospital/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.views.generic import ListView, DetailView, TemplateView
from .models import Doctor


class hospitalView(TemplateView):
    template_name = 'index.html'


class DoctorListView(ListView):
    queryset = Doctor.objects.all()
    template_name = 'doctor-team.html'



class ContactView(TemplateView):
    template_name = 'contact.html'
    
    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        email_from = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        if subject == '':
            subject = 'Healthcae Contact'     

        if name and message and email_from:
            send_mail(
                subject+ " - " + name,
                message+ 
                email_from,
                ['yourname@gmail.com',],
                fail_silently=False,
            )
            messages.success(request, f'Your message has been sent. Thank you {name}!')

        return redirect('contact')

appointment/templates/appointment/appointments.html
{% extends '_base.html' %}
{% load static %}
{% block maincontent %}
<div class="col-md-5">
  <ol class="breadcrumb">
    <li><a href="">Home</a></li>
    <li class="active">Appointment</li>
  </ol>
</div>
  <!--contact-->
  <section id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="ser-title">Get Appointment</h2>
          <hr class="botm-line">
        </div>

        <div class="col-md-12 col-sm-8 ">
          <div class="contact-info">
            <h3 class="cnt-ttl">Having Any Query! Or Book an appointment</h3>
            <div class="space"></div>

            {% if messages %}
            <div class="w-full text-white bg-green-500">
                <div class="container flex items-center justify-between px-6 py-4 mx-auto">
                    <div class="flex">
                        <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                            <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667 23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z"></path>
                        </svg>
                        {% for message in messages %}
                        <p class="mx-3">{{ message }}</p>
                        {% endfor %}
                    </div>

                    <button class="p-1 transition-colors duration-200 transform rounded-md hover:bg-opacity-25 hover:bg-gray-600 focus:outline-none">
                        <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M6 18L18 6M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </button>
                </div>
            </div>
            {% else %}

              <form action="{% url 'appointment' %}" method="post" role="form" class="contactForm">
                  {% csrf_token %}
                  <div class="form-group">
                    <input type="text" name="name" class="form-control br-radius-zero" id="name" placeholder="Full Name *" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                    <div class="validation"></div>
                  </div>
                  <div class="form-group">
                    <input type="text" class="form-control br-radius-zero" name="phone" id="subject" placeholder="Your Phone *" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                    <div class="validation"></div>
                  </div>
                  <div class="form-group">
                    <input type="email" class="form-control br-radius-zero" name="email" id="email" placeholder="Your Email *" data-rule="email" data-msg="Please enter a valid email" />
                    <div class="validation"></div>
                  </div>

                <div class="form-group" >
                <select name="doctor" class="form-control">
                  <option>--Doctor--</option>
                  {% for doctor in doctors %}
                  <option value="{{ doctor.id }}">{{ doctor.name }}</option>
                  {% endfor %}
                </select>
                </div>

                <div class="form-group">
                <select name="time" class="form-control">
                    <option disabled>--Time--</option>
                    <option value="morning">Morning</option>
                    <option value="morning">Evening</option>
                </select>
                </div>

                <div class="form-group">
                <div class="input-group date">
                    <input placeholder="Date *" name="date" class="form-control" type="date">
                    <span class="input-group-addon"></i> </span> </div>
                </div>

                <div class="form-group">
                    <textarea class="form-control br-radius-zero" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Extra Note..."></textarea>
                    <div class="validation"></div>
                </div>

                <div class="form-action">
                  <button type="submit" class="btn btn-form">Book Appointment</button>
                </div>
              </form>
            {% endif %}

          </div>
        </div>

      </div>
    </div>
  </section>
  <!--/ contact-->


<!--Footer Start-->
{% include '_footer.html' %}
<!--Footer End-->
{% endblock maincontent %}

templates/_base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Medilab</title>
  <meta name="description" content="Free Bootstrap Theme by BootstrapMade.com">
  <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
  {% include '_css.html' %}

</head>

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">
  <!--banner-->
  <section id="banner" class="banner">
    <div class="bg-color">
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="col-md-12">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				        <span class="icon-bar"></span>
				      </button>
              <a class="navbar-brand" href="#"><img src="{% static 'img/logo.png' %}" class="img-responsive" style="width: 140px; margin-top: -16px;"></a>
            </div>
            <div class="collapse navbar-collapse navbar-right" id="myNavbar">
              <ul class="nav navbar-nav">

                <li class=""><a href="{% url 'hospital' %}">Home</a></li>
                <li class=""><a href="#service">Services</a></li>
                <li class=""><a href="{% url 'doctor_team' %}">Doctors</a></li>
                <li class=""><a href="">About</a></li>
                <li class=""><a href="#testimonial">Testimonial</a></li>
                <li class=""><a href="{% url 'contact' %}">Contact</a></li>
              </ul>
            </div>
          </div>
        </div>
      </nav>
      <div class="container">
        <div class="row">
          <div class="banner-info">
            <div class="banner-logo text-center">
              <img src="{% static 'img/logo.png' %}" class="img-responsive">
            </div>
            <div class="banner-text text-center">
              <h1 class="white">Healthcare at your desk!!</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod <br>tempor incididunt ut labore et dolore magna aliqua.</p>
              <a href="{% url 'appointment' %}" class="btn btn-appoint">Make an Appointment.</a>
            </div>
            <div class="overlay-detail text-center">
              <a href="#service"><i class="fa fa-angle-down"></i></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ banner-->
  
    {% block maincontent %}
        
    {% endblock maincontent %}
        


  {% include '_js.html' %}

</body>

</html>

templates/_css.html
{% load static %}
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans|Raleway|Candal">
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">

templates/_footer.html
<!--footer-->
  <footer id="footer">
    <div class="top-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Quick Links</h4>
            </div>
            <div class="info-sec">
              <ul class="quick-info">
                <li><a href="index.html"><i class="fa fa-circle"></i>Home</a></li>
                <li><a href="#service"><i class="fa fa-circle"></i>Service</a></li>
                <li><a href="#contact"><i class="fa fa-circle"></i>Appointment</a></li>
              </ul>
            </div>
          </div>
        <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Expert Doctors</h4>
            </div>
            {% for doctor in object_list|slice:':3' %}
            <div class="info-sec">
              <ul class="quick-info">
                <li><a href="{% url 'doctor_team'  %}">
                <i class="fa fa-circle"></i>Dr. {{ doctor.name }}</a></li>
              </ul>
            </div> 
            {% endfor %}
          </div>
          <div class="col-md-4 col-sm-4 marb20">
            <div class="ftr-tle">
              <h4 class="white no-padding">Follow us</h4>
            </div>
            <div class="info-sec">
              <ul class="social-icon">
                <li class="bglight-blue"><i class="fa fa-facebook"></i></li>
                <li class="bgred"><i class="fa fa-google-plus"></i></li>
                <li class="bgdark-blue"><i class="fa fa-linkedin"></i></li>
                <li class="bglight-blue"><i class="fa fa-twitter"></i></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer-line">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            © Copyright Medilab Theme. All Rights Reserved
            <div class="credits">
              Designed by <a href="https://bootstrapmade.com/">BootstrapMade.com</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </footer>
<!--/ footer-->

templates/_js.html
{% load static %}
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'contactform/contactform.js' %}"></script>

templates/about.html
<!--about-->
  <section id="about" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-12">
          <div class="section-title">
            <h2 class="head-title lg-line">The Medilap <br>Ultimate Dream</h2>
            <hr class="botm-line">
            <p class="sec-para">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..</p>
            <a href="" style="color: #0cb8b6; padding-top:10px;">Know more..</a>
          </div>
        </div>
        <div class="col-md-9 col-sm-8 col-xs-12">
          <div style="visibility: visible;" class="col-sm-9 more-features-box">
            <div class="more-features-box-text">
              <div class="more-features-box-text-icon"> <i class="fa fa-angle-right" aria-hidden="true"></i> </div>
              <div class="more-features-box-text-description">
                <h3>It's something important you want to know.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Ut wisi enim ad minim veniam, quis nostrud.</p>
              </div>
            </div>
            <div class="more-features-box-text">
              <div class="more-features-box-text-icon"> <i class="fa fa-angle-right" aria-hidden="true"></i> </div>
              <div class="more-features-box-text-description">
                <h3>It's something important you want to know.</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et. Ut wisi enim ad minim veniam, quis nostrud.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ about-->

   <!--cta 2-->
  <section id="cta-2" class="section-padding">
    <div class="container">
      <div class=" row">
        <div class="col-md-2"></div>
        <div class="text-right-md col-md-4 col-sm-4">
          <h2 class="section-title white lg-line">« A few words<br> about us »</h2>
        </div>
        <div class="col-md-4 col-sm-5">
          Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a typek
          <p class="text-right text-primary"><i>— Medilap Healthcare</i></p>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </section>
  <!--cta-->

templates/contact.html
{% extends '_base.html' %}

{% load static %}
{% block maincontent %}
<div class="col-md-5">
  <ol class="breadcrumb">
    <li><a class="text-primary" href="{% url 'hospital' %}">Home</a></li>
    <li class="text-primary">Contact</li>
  </ol>
</div>
  <!--contact-->
  <section id="contact" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="ser-title">Contact us</h2>
          <hr class="botm-line">
        </div>
        <div class="col-md-4 col-sm-4">
          <h3>Contact Info</h3>
          <div class="space"></div>
          <p><i class="fa fa-map-marker fa-fw pull-left fa-2x"></i>321 Awesome Street<br> New York, NY 17022</p>
          <div class="space"></div>
          <p><i class="fa fa-envelope-o fa-fw pull-left fa-2x"></i>info@companyname.com</p>
          <div class="space"></div>
          <p><i class="fa fa-phone fa-fw pull-left fa-2x"></i>+1 800 123 1234</p>
        </div>
        <div class="col-md-8 col-sm-8 marb20">
          <div class="contact-info">
            <h3 class="cnt-ttl">Get in Touch</h3>
            <div class="space"></div>
            {% if messages %}
            <div class="w-full text-white bg-green-500">
                <div class="container flex items-center justify-between px-6 py-4 mx-auto">
                    <div class="flex">
                        <svg viewBox="0 0 40 40" class="w-6 h-6 fill-current">
                            <path d="M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667 29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667 23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z"></path>
                        </svg>
                        {% for message in messages %}
                        <p class="mx-3">{{ message }}</p>
                        {% endfor %}
                    </div>

                    <button class="p-1 transition-colors duration-200 transform rounded-md hover:bg-opacity-25 hover:bg-gray-600 focus:outline-none">
                        <svg class="w-5 h-5" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M6 18L18 6M6 6L18 18" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                        </svg>
                    </button>
                </div>
            </div>
            {% else %}

            <form action="{% url 'contact' %}" method="post" role="form" class="contactForm">
                {% csrf_token %}
                <div class="form-group">
                  <input type="text" name="name" class="form-control br-radius-zero" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control br-radius-zero" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control br-radius-zero" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                  <div class="validation"></div>
                </div>
                <div class="form-group">
                  <textarea class="form-control br-radius-zero" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                  <div class="validation"></div>
                </div>

                <div class="form-action">
                  <button type="submit" class="btn btn-form">Send Message</button>
                </div>
            </form>
          {% endif %}

          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ contact-->

<!--Footer Start-->
{% include '_footer.html' %}
<!--Footer End-->
{% endblock maincontent %}

templates/doctor-team.html
{% extends '_base.html' %}
{% load static %}
{% block maincontent %}
  <div class="col-md-5">
    <ol class="breadcrumb">
      <li><a class="text-primary" href="{% url 'hospital' %}">Home</a></li>
      <li class="text-primary">Doctors</li>
    </ol>
  </div>
  <!--doctor team-->
  <section id="doctor-team" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2 class="ser-title">Meet Our Doctors!</h2>
          <hr class="botm-line">
        </div>
        {% for doctor in object_list %}
        <div class="col-md-3 col-sm-3 col-xs-6">
          <div class="thumbnail">
            <img src="{{ doctor.picture.url }}" alt="{{ doctor.name }}" class="team-img">
            <div class="caption">
              <h3>Dr. {{ doctor.name }}</h3>
              <p>{{ doctor.speciality}}</p>
              <ul class="list-inline">
                {% if doctor.facebook %}
                <li><a href="{{ doctor.facebook }}"><i class="fa fa-facebook"></i></a></li>
                {% endif %}
                {% if doctor.twitter %}
                <li><a href="{{ doctor.twitter }}"><i class="fa fa-twitter"></i></a></li>
                {% endif %}
                {% if doctor.instagram %}
                <li><a href="{{ doctor.instagram }}"><i class="fa fa-instagram"></i></a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!--/ doctor team-->

{% endblock maincontent %}

templates/index.html
{% extends '_base.html' %}

<!--Maincontent Start-->
{% block maincontent %}

    <!--Services Start-->
    {% include 'services.html' %}
    <!--Services End-->


    <!--Shedule Start-->
    {% include 'schedule.html' %}
    <!--Shedule End-->

    <!--About End-->
    {% include 'about.html' %}
    <!--About End-->

    <!--Testimonial End-->
    {% include 'testimonial.html' %}
    <!--Testimonial End-->


    <!--Footer Start-->
    {% include '_footer.html' %}
    <!--Footer End-->

{% endblock maincontent %}

<!--Maincontent End-->

templates/schedule.html
<!--cta-->
  <section id="cta-1" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="schedule-tab">
          <div class="col-md-4 col-sm-4 bor-left">
            <div class="mt-boxy-color"></div>
            <div class="medi-info">
              <h3>Emergency Case</h3>
              <p>I am text block. Edit this text from Appearance / Customize / Homepage header columns. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
              <a href="#" class="medi-info-btn">READ MORE</a>
            </div>
          </div>
          <div class="col-md-4 col-sm-4">
            <div class="medi-info">
              <h3>Emergency Case</h3>
              <p>I am text block. Edit this text from Appearance / Customize / Homepage header columns. Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
              <a href="#" class="medi-info-btn">READ MORE</a>
            </div>
          </div>
          <div class="col-md-4 col-sm-4 mt-boxy-3">
            <div class="mt-boxy-color"></div>
            <div class="time-info">
              <h3>Opening Hours</h3>
              <table style="margin: 8px 0px 0px;" border="1">
                <tbody>
                  <tr>
                    <td>Monday - Friday</td>
                    <td>8.00 - 17.00</td>
                  </tr>
                  <tr>
                    <td>Saturday</td>
                    <td>9.30 - 17.30</td>
                  </tr>
                  <tr>
                    <td>Sunday</td>
                    <td>9.30 - 15.00</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--cta-->

templates/services.html
  <!--service-->
  <section id="service" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-sm-4">
          <h2 class="ser-title">Our Service</h2>
          <hr class="botm-line">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris cillum.</p>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-stethoscope"></i>
            </div>
            <div class="icon-info">
              <h4>24 Hour Support</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-ambulance"></i>
            </div>
            <div class="icon-info">
              <h4>Emergency Services</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-4">
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-user-md"></i>
            </div>
            <div class="icon-info">
              <h4>Medical Counseling</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
          <div class="service-info">
            <div class="icon">
              <i class="fa fa-medkit"></i>
            </div>
            <div class="icon-info">
              <h4>Premium Healthcare</h4>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--/ service-->

templates/testimonial.html
{% load static %}
<!--testimonial-->
  <section id="testimonial" class="section-padding">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          HAPPY PATIENTS
          <h2 class="ser-title">see what patients are saying?</h2>
          <hr class="botm-line">
        </div>
        {% for testimonial in testimonial_list %}
        <div class="col-md-4 col-sm-4">
          <div class="testi-details">
            <!-- Paragraph -->
            <p>{{ testimonial.description }}</p>
          </div>
          <div class="testi-info">
            <!-- User Image -->
            <a href="#"><img src="{{ testimonial.image.url }}" alt="{{ testimonial.title}}" class="img-responsive"></a>
            <!-- User Name -->
            <h3>{{ testimonial.title}}<span></span></h3>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>
  <!--/ testimonial-->